// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fztbadluchxixxbmvdtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6dGJhZGx1Y2h4aXh4Ym12ZHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzIxODMsImV4cCI6MjA1NzU0ODE4M30.xVgF_jwtAVvpKRABrxt7Ad5F6v20ToA9cqjS3mPlP1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);